### ISSUE TITLE
Stumbled into Macaque

### ISSUE THREAD

**Issue by enzyme69** [MonkeyGone2Heaven/MacaqueBlender#2]
I am curious about this project you are doing, so you have Blender project all setup in Python? Is there a complete Blend files that I could test to see the rig, etc?

**Comment by Phenomenal-Cat** [comment]
Hi Jimmy. Unfortunately the .blend file is not currently publicly available, but I hope to make it available after we've published our first research paper using it. In the meantime we're inviting scientific researchers to contact us if they are interested in accessing the model through a collaboration. Thanks.

**Comment by iandol** [comment]
@MonkeyGone2Heaven - Hi Aiden, I'd be interesting in discussing a collaboration, what is the best way to contact you?

**Comment by jurididevich** [comment]
Hi Aiden, I am working on a research (vision physiology lab) at the Pavlov Institute of Physiology, with macaque rhesus. In May-June, we have a series of experiments with an invasive interface and we would like to try MacaqueBlender for visual stimulation. Is it possible? Thanks.
